### PR TITLE
Migrated to core clr. This version is compatible with both- net 4.5.1…

### PR DESCRIPTION
**Pull request by bilal-fazlani**
I have migrated this repository to CoreCLR. It's still compatible with .net 4.5.1 and all unit tests are passing on local machine.

### CODE REVIEW

**Comment by bilal-fazlani** [comment]
this is also related to https://github.com/Pereingo/statsd-csharp-client/issues/50

**Comment by DarrellMozingo** [comment]
Hey Bilal,

Thanks a lot for this PR! I've not done that much with the core clr yet, so it's very helpful.

How can I get this running locally to try out?

I see you used `Socket.SendToAsync()` which bubbled up everywhere. Can I ask why? At the very least I think async overloads for the public API are needed for backwards compatibility. I see a sync version of `SendTo()` is [still available](https://github.com/dotnet/corefx/blob/master/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs#L1399).

Thanks!

**Comment by bilal-fazlani** [comment]
Hi @DarrellMozingo 

Some methods like Dns.GetHostEntryAsync(_name); are not syncronos. But if you are a real fan of backward compatibility, I can make it backward compatible. Just to show you how it is done, have a look below:

```csharp
    public interface IStatsdUDP
    {
        Task SendAsync(string command);

#if NET451
        void Send(string command);
#endif
    }
```

After compiling code like this, when you refer IStatsdUDP from a .net 4.5.1 project, you see both sync and async methods available to you. And when you refer to IStatsdUDP from a coreclr project, you only see async method available.

This is how other libraries have ported their projects to mono and coreclr. **Since it will take some time make it backward compatible, I will only spend time on it if you feel this approach is okay.**

Once this is accomplished, to make sure the functionality works as expected, I would suggest we write unit tests for both platforms separately in separate unit test projects.

The advantage of doing this would be users will have to install the same nuget package no matter what platform they are targeting. And the tradeoff of this type of backward compatibility is the mess it creates in code. But I have started to live with this now.

Let me know!

**Comment by bilal-fazlani** [comment]
After you pointed out that SendTo() method is still available, I think all platforms can have access async and async methods. 

There is only one public method i.e. `public static void Configure(MetricsConfig config)` in `Metrics` class, that will only be available in dot net 4.5.1. And `ConfigureAsync(MetricsConfig config)` will be in both platforms. 

I am creating a partial class for synchronous methods to avoid mess in the same file.

**Comment by DarrellMozingo** [comment]
Perfect, thanks for that Bilal. Yes, I think backwards compatibility is worth it at the expense of slightly more cumbersome code. Glad you found a nice shim to make it happen. I'll take a look this weekend!

**Comment by bilal-fazlani** [comment]
Hi Darrel,
It's a work in progress. I have found that the async 'send' for udp that is
available to .net 4.5.1 is not the task based asnc but callback based
async.

So I decided to add the async only for core clr so that core clr shall
support both sync and async while .net 4.5.1 users will have only sync api.
For now.

I am in the process of making these changes and writing unit tests for
platforms separately.

Don't look at it right now as its not complete code. I will update you when
its worth looking. I plan to work on it in the weekend.

**Comment by DarrellMozingo** [comment]
Sounds good!

**Comment by bilal-fazlani** [comment]
Okay the code is stable enough now. Please have a look at it. 
As I said earlier, All methods for net451 are synchronous. And supports async and sync for coreclr.
Unit tests work as expected for net451.
But I have not written any unit tests for coreclr. I would appreciate if someone can help me with it.

**Comment by DarrellMozingo** [comment]
Nice work Bilal, I'll take a look today and tomorrow.

**Comment by CumpsD** [comment]
What a timing :) just today I was looking for this, and here's a PR nearly done for it! Looking forward for it, thanks :)

**Comment by CumpsD** [comment]
@darrellmozingo did you had any time to take a look?

**Comment by DarrellMozingo** [comment]
I started too but might take me a bit longer (at least another 2 weeks, on holiday this week). Sorry, new to .net core and I want to make sure there's not too many breaking changes for clients so it's taking me a bit longer. If you need it sooner I'd suggest building bilal's branch :)

**Comment by bilal-fazlani** [comment]
@CumpsD  I have uploaded a nuget package of my branch temporarily. you can find it [here](https://www.nuget.org/packages/StatsdClient.Core/). Once we make this package core clr compatible, I plan to delete that nuget package. But the api will remain same so it's safe to use it for now. Hope that helps.

**Comment by bilal-fazlani** [comment]
@DarrellMozingo  what do u think about releasing this as a alpha or beta package so that we get some feedback ?
Also, did you get to spent some time reviewing code ? Sorry for nagging you again n again. :P

**Comment by DarrellMozingo** [comment]
Sorry for the slow feedback @bilal-fazlani!

Where can get I get the `rc2` version of the `System.Net.*` and `System.Text.Encoding` dependencies listed in `project.json`? It fails to restore for me, and Nuget.org only lists various [`beta` versions](https://www.nuget.org/packages/System.Net.Sockets)?

Also, how do you run the tests under dotnet core?

**Comment by bilal-fazlani** [comment]
ahh, ok. sorry about rc2 thing. I will get back to you on this

**Comment by bilal-fazlani** [comment]
there is a separate nuget source for rc2, but we should not use it is officially released. I will use rc1 and make a commit.

**Comment by bilal-fazlani** [comment]
I have upgraded to RC2 of Dotnet core and removed dependencies of unofficial nuget sources. 

But looks like this code base is ahead of mine now. I will try to sync and update this pull request.

**Comment by wjdavis5** [comment]
brilliant cant wait

**Comment by RTodorov** [comment]
Hello guys,

Is this project still alive? Would be great to have this PR merged/released/finished if possible.

Cheers

**Comment by DarrellMozingo** [comment]
Not as terribly active any more. Would you be interested in doing a review on this PR @RTodorov? Haven't done any .net core myself.

**Comment by pekiZG** [comment]
Hi all,
It would be great that we do this if there are no breaking changes.

As @DarrellMozingo wrote someone with experience should do the review

**Comment by RTodorov** [comment]
I'll take a look on it guys, it will probably need some adjustment since .NET Core 1.0 was released after this PR was opened. Will let you know.

**Comment by pekiZG** [comment]
@RTodorov Did you had time to do peer review?

**Comment by pekiZG** [comment]
What is the status on this?

**Comment by DarrellMozingo** [comment]
There's another PR coming in with some newer core features so I'll go ahead and close this. Thanks so much to everyone that put time in on this, it's very much appreciated. Sorry we couldn't get it in!

**Pull request closed without merging**
